name: resize

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  resize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Install Libvips library
        run: |      
          sudo apt-get update -y
          sudo apt-get install -y libvips
      - name: Install PIP
        run: |
          curl  https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          python3 get-pip.py
          python3 -m pip install --user pyvips
          rm get-pip.py
      - name: Resize test image
        run: |
          echo Testing resize script
          python3 ./resize.py
      - name: Update new files
        uses: mikeal/publish-to-github-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
