name: resize

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  resize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Resize test image
        run: |
          echo Testing resize script
          echo python3 resize.py
